### ISSUE TITLE
Unnecessary '\n' character

### ISSUE THREAD

**Issue by olegafx** [dgorissen/coursera-dl#1]
Completed quiz in video-lecture adds a "\nQuiz Attempted" label. It contains unnecessary '\n' character . '\n' produces fail in mkdir operation on Windows.

**Comment by dgorissen** [comment]
Added another check for this case as well as for non printable chars which may sneak through. If there are still issues now Ill switch to a whitelist approach.
Let me know if it works for you.

**Comment by olegafx** [comment]
Yep, it works now. Thanks.

**Comment by olegafx** [comment]
I found that "Writing in the Sciences" course uses ' " ' symbol. List of illegal symbols in Windows file names:
\ / : \* ? " < > |

I think that you accidentally deleted " from source code, because I see it in diff :)
345     
-    return re.sub('[:\?\\/<>*"]', '', s).strip()
   349  
-    return re.sub('[:\?\\/<>*\r\n]', '', s).strip()

**Comment by dgorissen** [comment]
noooooo! :) Switched to a whitelist, have another shot.
