### ISSUE TITLE
bad file names

### ISSUE THREAD

**Issue by rm-v** [dgorissen/coursera-dl#101]
I get file names with url encoded special characters like 20 in place of spaces etc.
For example when dowloading course: model thinking i get:
120-20120-20Lecture201.12920Why20Model3F202883A5329.mp4 
instead: 
1 - 1 - Lecture 1.1) Why Model (853).mp4

OS: Windows 7
Pyhon2.7
coursera-dl installed via: pip install coursera-dl

**Comment by dgorissen** [comment]
assuming same as #99, is fixed
