### ISSUE TITLE
should download coursework also

### ISSUE THREAD

**Issue by zendeavor** [dgorissen/coursera-dl#103]
downloading the videos is pretty convenient, and bringing the subtitles along with it is a nice touch. however, this still leaves a lot to be desired for courses like https://www.coursera.org/course/programdesign where each week's coursework is broken up into many small starter files. this is not optional information, and requires that i go through some rather painful efforts to download each tiny little file one-by-one so that i can get started on the homework that accompanies the lectures.

**Comment by dgorissen** [comment]
Unfortunately there is no easy way around this as conventions vary between courses. You would really have to do some advanced scraping, something I do not have the time for to implement. If you are following the course along it should not be too bad though.
