### ISSUE TITLE
Error: ImportError: cannot import name PY2

### ISSUE THREAD

**Issue by Robottinosino** [dgorissen/coursera-dl#106]
from six import print_, PY2
ImportError: cannot import name PY2

GNU/Linux (kernel 3.2.0-4-686-pae) DebianEdu/Skolelinux
Python 2.7.3
courseradownloader _version_info__ = (1,5,1)

**Comment by xu-cheng** [comment]
Do you install the package `six`?

**Comment by xu-cheng** [comment]
Your six version is too old. Current version is 1.4. I recommend you upgrade it using pip.

**Comment by Robottinosino** [comment]
On 07/11/2013 17:29, Xu Cheng wrote:

> Your six version is too old. Current version is 1.4. I recommend you
> upgrade it using pip.

You are right.

Using 1.4 gets rid of that particular error message and solves the problem.

Debian stable's packages are conservatively upgraded and the Wheezy 
version was a bit too old.

Thank you.

PS: I find it confusing to use both PIP and APT-GET to manage libraries 
so I just downloaded and extracted the library and updated PYTHONPATH 
accordingly.

Issue closed.

**Comment by dgorissen** [comment]
My experience is to always use pip. Avoid using the system package manager
for python pkgs. Easier to manager.

---

Web    : http://dirkgorissen.com
Twitter : https://twitter.com/elazungu

**Comment by Robottinosino** [comment]
I see why would you feel that way but a valid argument is also the exact converse: the system already uses one package manager, why introduce another one? Before using PIP, perhaps a Debian user should consider making a dpkg of an updated library and distribute it locally as an APT source. Both approaches are tricky when having to flip from one development environment (i.e. a project using a set of libraries with particular dependencies) to another quickly, perhaps multiple times per day. Perhaps you are using https://pypi.python.org/pypi/virtualenv or similar? Mind you, I don't like updating PYTHONPATH ad-hoc either, the above was just a quick hack to force one version over another.
