### ISSUE TITLE
Download subtitles in the language specified from command line

### ISSUE THREAD

**Issue by yehezkielbs** [dgorissen/coursera-dl#110]
For example, the video of this course https://www.coursera.org/course/calvin is in french, but it has 2 subtitles: french & english.

The published link on the course page (https://class.coursera.org/calvin-001/lecture/index) is only french subtitle, for example : https://class.coursera.org/calvin-001/lecture/subtitles?q=55_fr&format=srt . The english version of that subtitle is just to replace "fr" with "en" https://class.coursera.org/calvin-001/lecture/subtitles?q=55_en&format=srt

The script wouldn't be able to detect what languages are available to download, so the users have to specify that they want to download the "en" version, for example.

**Comment by yehezkielbs** [comment]
- Accidentally clicked close button -

**Comment by dgorissen** [comment]
I see this was never commented on. Could be useful and not too invasive to change but out of scope for me currently. Happy to review pull requests though.
