### ISSUE TITLE
fail to create a folder with long name correctly

### ISSUE THREAD

**Issue by negef** [dgorissen/coursera-dl#119]
System: windows 7
executed command: coursera-dl marketing-001 -u xxxx@email.com -p *****

problem description: 

coursera-dl created a folder with name 
"08 - (Week 8) GO TO MARKET STRATEGIES How to Find Lead Users and Facilitate Influence and Co",

but the name is supposed to be
"08 - (Week 8) GO TO MARKET STRATEGIES How to Find Lead Users and Facilitate Influence and Contagion".

And it showed:

WindowsError: [Error 3] The system cannot find the path specified: 'C:\temp\ma
rketing-001\08 - (Week 8) GO TO MARKET STRATEGIES How to Find Lead Users and Facilitate Influence and Co...\01 - (1) Brands and Digital Marketing (14-01)'

I have tried to manually change the folder name but that didn't work.

Thanks,
Ben
# 
- Downloading resources for (10) Preference Isolation (14-36)
  - "Module 7-10.pdf" already exists, skipping
  - "8 - 10 - (10) Preference Isolation (1436).mp4" already exists, skipping
  - (Week 8) GO TO MARKET STRATEGIES How to Find Lead Users and Facilitate Influence and Co...
    Traceback (most recent call last):
    File "C:\python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.5.1', 'console_scripts', 'coursera-dl')()
    File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
    line 578, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gz
    ip_courses = args.gzip_courses)
    File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
    line 421, in download_course
    os.makedirs(clsdir)
    File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
    WindowsError: [Error 3] The system cannot find the path specified: 'C:\temp\ma
    rketing-001\08 - (Week 8) GO TO MARKET STRATEGIES How to Find Lead Users and Fa
    cilitate Influence and Co...\01 - (1) Brands and Digital Marketing (14-01)'

**Comment by dgorissen** [comment]
Use the current master branch and see the mppl argument

**Comment by negef** [comment]
Thanks for your reply. I am fairly new to python and programming language.
Could you explain a bit more what is "master branch" and "mppl argument"?

Thanks, negef

-- Ben

**Comment by dgorissen** [comment]
Use the download zip button on https://github.com/dgorissen/coursera-dl
Install pip if you have not already (http://www.pip-installer.org/)
Install all the dependencies: pip install -U -r requirements.txt
run python courseradownloader/courseradownloader.py and look at the help text

**Comment by liz425** [comment]
It's really nice to get this tool.
I've encountered the same problem, and I've already set the "mppl" variable to 240.
But it's still not long enough for specific videos in some courses.
I really appreciate that if you could improve the naming rules, which can shorten the name of videos automatically when out of resources.
BTW, the tool is awesome and really saving lots of time on it. Thks~

**Comment by dgorissen** [comment]
mppl means the maximum length of a path segment, so it should be set smaller not larger. e.g., 70.
Also ensure you upgrade to the latest version which is just released.
