### ISSUE TITLE
Getting Error when installing 

### ISSUE THREAD

**Issue by 403Penguin** [dgorissen/coursera-dl#123]
Getting some issue about utf8 encoding. Not a expert in python so not sure.

traceback (most recent call last):
  File "setup.py", line 20, in <module>
    long_description=open("README.md").read(),
  File "/usr/lib/python3.3/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 115: ordinal not in range(128)

**Comment by dgorissen** [comment]
Can you confirm this happens with the current git master branch? Also
please provide the full output log.

**Comment by 403Penguin** [comment]
Downloading from URL https://pypi.python.org/packages/source/c/coursera-dl/coursera-dl-1.5.1.tar.gz#md5=5a9d87a6808f4b6e2ead25489166f00f (from https://pypi$
  Running setup.py (path:/tmp/pip_build_david/coursera-dl/setup.py) egg_info for package coursera-dl
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_david/coursera-dl/setup.py", line 20, in <module>
        long_description=open("README.md").read(),
      File "/usr/lib/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 115: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_david/coursera-dl/setup.py", line 20, in <module>

```
long_description=open("README.md").read(),
```

  File "/usr/lib/python3.3/encodings/ascii.py", line 26, in decode

```
return codecs.ascii_decode(input, self.errors)[0]
```

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 115: ordinal not in range(128)

**Comment by AdrianYu** [comment]
As far as I know, this program cannot be installed under the latest python 2.7.6. You may try install python 2.7.3 first.

**Comment by dgorissen** [comment]
It should work with latest python. I meant to use the latest version from github. Not the latest version from pypi. Anyway, I have just updated the version in pypi anyway so do a pip install --upgrade. If it still crashes please provide the full log.
