### ISSUE TITLE
can not download videos, only two files: index.html and lectures.html

### ISSUE THREAD

**Issue by thinkall** [dgorissen/coursera-dl#13]
![coursera-dl-error](https://f.cloud.github.com/assets/3197038/45736/8a482510-57cb-11e2-872d-b259ad7c6e18.png)

I tried the command in the picture, but only got two files: 'index.html' and 'lectures.html', 

the course "Think again" is in Week 7.  

Other finished courses  like "Model Thinking"  also had this problem.

I can't watch youtube video directly, usually I will use proxy, maybe this is the reason. But I don't know how to set proxy for coursera-dl, so I can't  confirm it.

**Comment by caspik** [comment]
have the same problem

**Comment by dgorissen** [comment]
coursera just redesigned their site which broke the script. I did a quick fix, see if it works now.

**Comment by Anrock** [comment]
Same problem right now. Redesigned again?

**Comment by dgorissen** [comment]
yup, I am actively fixing this now

update: I have a fix but ran into a problem with one of the libraries Im using (spynner), fix blocked until thats solved

**Comment by dgorissen** [comment]
Ok, I think I have fixed it, at the cost of a new dependency on pyqt.. Not ideal but it did allow me to keep most of the other code unchanged, minimizing the chance of breaking something else. Will try to refactor this further in the future.

Closing issue now, please test and repoen if you still have problems.

Edit: while it worked it required a dependency on pyqt, this has now been removed again as a better solution was found.

**Comment by rodch-us** [comment]
Is it working for anyone else? I am getting errors in login and timeouts - any idea what am I doing wrong here?

here is dump from my Win7 machine, showing errors:

c:>python.exe courseradownloader.py -u XXX@yahoo.com -p XXXXX precalculus-001
HTML parser set to lxml
- Authenticating as xxxxx@yahoo.com...
  Traceback (most recent call last):
  File "courseradownloader.py", line 488, in <module>
    main()
  File "courseradownloader.py", line 481, in main
    d.login()
  File "courseradownloader.py", line 86, in login
    res = wait_for_content(lambda s: s.findAll(class_="coursera-profile-listing-
  sections"))
  File "courseradownloader.py", line 72, in wait_for_content
    webkit.wait_for_content(can_continue, 5, "Timout reached, please check your
  network and username/password", delay=2)
  File "c:\python27\lib\site-packages\spynner\browser.py", line 868, in wait_for
  _content
  raise SpynnerTimeout(msg)
  spynner.browser.SpynnerTimeout: SPYNNER waitload: Timeout reached: 5 retries for
  2s delay.
  Timout reached, please check your network and username/password
  QWaitCondition: Destroyed while threads are still waiting

**Comment by cdoremus** [comment]
I get the same results (only html files download) for dataanalysis-001 and maththink-002. I am using Python 2.7.3 on Windows XP.

**Comment by danzean** [comment]
## I am unable to download as well. It quits after downloading two pages and exits to the terminal prompt. Here's what I am getting:

Warning: lxml not available, falling back to built-in 'html.parser' (see -q option), this may cause problems on Python < 2.7.3
HTML parser set to html.parser
- Authenticating as xxxxx@yahoo.com...
- Already logged in
- Collecting downloadable content from http://class.coursera.org/sciwrite-2012-001/lecture/index
- Got all downloadable content for sciwrite-2012-001
- sciwrite-2012-001 will be downloaded to /Users/xxxx/test/sciwrite-2012-001
  - Downloading lecture/syllabus pages
    - "index.html" 
    - "lectures.html" 
      MacBook-Pro:$

**Comment by dgorissen** [comment]
Please use the latest version. Should all work now.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by togaurav** [comment]
I ran the latest script but still getting the same issue...
I am using Python 2.7.3 version.

stack trace::

D:\gaurav-git-repo\coursera-dl\courseradownloader>python.exe courseradownloader.py -u ********_@**_****\* -p *******\* -d F:\tech\coursera introACpartI-001
Warning: lxml not available, falling back to built-in 'html.parser' (see -q option), this may cause problems on Python < 2.7.3
HTML parser set to html.parser
- Authenticating as ********_@**_*****...
- Already logged in
- Collecting downloadable content from http://class.coursera.org/introACpartI-001/lecture/index
- Got all downloadable content for introACpartI-001
- introACpartI-001 will be downloaded to F:\tech\coursera\introACpartI-001
  - Downloading lecture/syllabus pages
    - "index.html" already exists, skipping
    - "lectures.html" already exists, skipping

**Comment by dgorissen** [comment]
works perfectly here, did you accept the honour code?

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by togaurav** [comment]
Thanks boss, I deleted the old script, and downloaded the new script then it started working
thank you guys

**Comment by dgorissen** [comment]
Ok, just to be sure here, I made some minor changes to log output. Can you
upgrade, run again, and paste the complete output.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu
