### ISSUE TITLE
Enhancement: --no-clobber [PATCH]

### ISSUE THREAD

**Issue by danmbox** [dgorissen/coursera-dl#132]
Added an option to skip existing files. Very handy when re-downloading the 2nd or 3rd time due to the "requests" mess (I usually run a script that identifies and removes broken files after coursera-dl finishes, then re-download)

(patch renamed as .png, seems to download fine; thanks, Github!)

![0001-added-no-clobber-arg](https://cloud.githubusercontent.com/assets/698115/2943831/b796ad08-d9c9-11e3-94aa-c95bf7d5b8e5.png)

**Comment by dgorissen** [comment]
Thanks for that, please submit a pull request.
