### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by joedicastro** [dgorissen/coursera-dl#137]
Since today I can't authenticate via this script to download the course materials, even when I can normally login in the website without problems. Probably something changed in the authentication mechanism at Coursera.

I get this error:

```
Coursera-dl v2.0.1 (html.parser)
Logging in as 'my@email'...
Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==2.0.1', 'console_scripts', 'coursera-dl')()
  File "build/bdist.linux-x86_64/egg/courseradownloader/courseradownloader.py", line 640, in main
  File "build/bdist.linux-x86_64/egg/courseradownloader/courseradownloader.py", line 111, in login
Exception: Failed to authenticate as my@email
```

**Comment by yehezkielbs** [comment]
+1

It's happening to me too. It's exactly the same exception.

**Comment by frnsys** [comment]
I've got this as well. Coursera responds with a 400 error when trying to login.

**Comment by gpby** [comment]
The same issue. 
To solve it try to replace in file courseradownloader.py 
line 99
LOGIN_FORM = {'email': self.username, 'password': self.password}
with
LOGIN_FORM = {'email': self.username, 'password': self.password, 'webrequest':'true'}

**Comment by emmaggie** [comment]
@gpby :+1:  This solved the issue described by @joedicastro on my machine (MacOS 10.9.4, coursera-dl v.2.0.1). Thank you!

**Comment by joedicastro** [comment]
@gpby This worked for me too! Thanks a lot! :ok:

**Comment by dgorissen** [comment]
Updated in master, thanks @gpby

**Comment by asmaarabie** [comment]
+1, worked

**Comment by dgorissen** [comment]
@asmaarabie note this issue is closed, just make sure you are running the latest release

**Comment by divijkumar** [comment]
I am seeing this issue again. I have verified that the coursera-dl, beautifulsoup4, mechanize & argparse are all updated and are at the latest versions. Am running on mac osx 10.9.5, python 2.7.5.

Coursera-dl v3.1 (html.parser)
Logging in as 'xyz@abc.com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 649, in main
    d.login(args.course_names[0])
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 168, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as xyz@abc.com

**Comment by lotard** [comment]
Ditto on Windows 7...
