### ISSUE TITLE
only download's syllabus

### ISSUE THREAD

**Issue by dpastoor** [dgorissen/coursera-dl#14]
Edit: has been fixed!

I used the script on a number of courses in mid december so I don't think it's a problem with my set-up.  When I run the script it:
- authenticates
- collects downloadable content from ...
- got all downloadable content for <class>

-downloading lecture/syllabus pages

Then ends the script.

Final result is a new folder created with only the syllabus link in it.

**Comment by Forever-Young** [comment]
It's fixed in https://github.com/dgorissen/coursera-dl/commit/f23095da5f03a84ec671926417519314329eef87

**Comment by dpastoor** [comment]
great!
