### ISSUE TITLE
Suddendly unable to login

### ISSUE THREAD

**Issue by McAldo** [dgorissen/coursera-dl#144]
I am on Ubuntu and have been happily using coursera-dl for months now, with .netrc credentials. Updated to latest version via PIP
It suddenly stopped being able to access:

I have the same problem with another software accessing Coursera, so I guess something must have changed on their side of things.

Credentials found in .netrc file
Logging in as 'myname@myemail.com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==2.0.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 640, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 111, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as myname@myemail.com

I read there is a workaround via the -c option, II exported my cookies.text file but I am unclear how to use it as -c is not an option with coursera-dl
"One can export a Netscape-style cookies file with a browser extension (1, 2) and use it with the -c option. This comes in handy when the authentication via password is not working (the authentication process changes now and then)."

**Comment by quux00** [comment]
I am having the exact same problem.  Also on Ubuntu.  Used coursera-dl many times in the past with no problem and now won't authenticate.  Tried 2 different coursers I'm currently enrolled in.

**Comment by bjnrtz** [comment]
I upgraded to current v2.0.2, worked again.

**Comment by McAldo** [comment]
Thanks for fixing this! 
upgraded with 
sudo pip install --upgrade coursera-dl 
and it all works great again :)
