### ISSUE TITLE
Files downloaded do not have same CRC as those downloaded through a browser

### ISSUE THREAD

**Issue by nick-s-b** [dgorissen/coursera-dl#149]
I've noticed that sometimes files that are downloaded with coursera-dl 2.0.2 are bigger than the files downloaded though a web browser. Sometimes, coursera-dl shows file download progress as over 100% (I noticed one at 190%).

Do not trust archives of videos/files downloaded through this version. It's simply unreliable and unstable.

**Comment by dgorissen** [comment]
Yes there are a bunch of issues with that version/branch and I do not have the time to fully investigate. Use the mechanize branch, while missing a few small things it is more robust and should work. See also #126

**Comment by dgorissen** [comment]
Updated mechanize branch, please test. If I hear no complaints I assume it works and I will update the pypi package.

**Comment by dgorissen** [comment]
pypi package updated. Closing issue. Report back if you still have problems.
