### ISSUE TITLE
Script no longer works

### ISSUE THREAD

**Issue by agug85** [dgorissen/coursera-dl#15]
Hello Dirk.
First of all many many thanks for your effort, that enabled me to follow various courses.
Sadly after the last modification done by Coursera to their site it's no more possible to download anything. In particular, I'm taking "Heterogeneous Parallel Programming" and "Think Again, how to reason and argue" and no more download is possible.
Can you fix someway your precious script?
TIA   -   Alberto

**Comment by abhinandkr** [comment]
About an hour ago, I downloaded the Game Theory week 1 content. Seems to be working fine. The command I used was as follows:
coursera-dl -u myusername -p mypassword -d D:\GameTheory\ gametheory-2012-002
where the last bit can be found from the URL of the course's homepage.

**Comment by agug85** [comment]
Sorry... I had only to upgrade the script!! Very stupid from me.
Thanks an please forgive me...

Alberto
