### ISSUE TITLE
File Paths Too Long Need Shortening

### ISSUE THREAD

**Issue by KCzar** [dgorissen/coursera-dl#152]
Some courses (particularly econ courses it seems) have videos with very long titles.  Because coursera-dl uses the full video name twice (once for the containing folder and once for the video itself) sometimes the file path exceeds the maximum file path length for Windows (260 characters).  When this happens, the download fails.  

Adding a step that determines the file path length and appropriately shortens the filename (I would propose leaving the folder name fully intact) would be very useful and probably very easy to accomplish.  

If I have some time I may give that a shot myself...

Love the package, thanks so much for putting that together!

**Comment by dgorissen** [comment]
This was covered in #8, see the mppl flag. Its a bit hackish though so pull requests welcome :)

**Comment by KCzar** [comment]
Ah, thanks! Sorry, I thought I had checked through all of the message board things.  I'll give it a shot, and happy to contribute if I find it lacking :).

Nice work on the package though - I now have almost 100 courses downloaded lol.  Previously I was doing it all manually...

Any tips on the best way to learn how to use the Mechanize package to its fullest extent?  I've gone through tutorials but have had trouble finding an adequate online published API.  And I still haven't figured out how to troubleshoot with the package.

Cheers,
Ken

Date: Mon, 22 Sep 2014 11:14:11 -0700

**Comment by dgorissen** [comment]
Cant really say more about mechanize than whats online Im afraid. If you feel ambitious you may also want to iron out issues with the master branch which uses requests instead of mechanize (see #126)
