### ISSUE TITLE
Add an option to download only given extensions

### ISSUE THREAD

**Issue by SebastianLopienski** [dgorissen/coursera-dl#160]
I'm usually interested in downloading _only_ PDF files. Now I have to use `-n` option to ignore other files - but I have to list (and know) all other file extensions. 

To address this use case, why don't we have an additional option, e.g.

```
  -i DOWNLOADFILES      comma-separated list of file extensions to download, e.g. "ppt,pdf"
```

... that would take precedence over the existing `-n` option:

```
  -n IGNOREFILES        comma-separated list of file extensions to skip, e.g. "ppt,srt,pdf"
```

What do you think? I can implement it if @dgorissen and others find it useful (=will merge :-)

**Comment by dgorissen** [comment]
Sure :)

**Comment by SebastianLopienski** [comment]
Here you go: #161  :-)

**Comment by SebastianLopienski** [comment]
I saw you already merged it; do you know when this update will be available via pip?

**Comment by dgorissen** [comment]
Sorry, Im swamped. If you submit PR with updated version & changelog files
I will merge and update pip

---

Dr. Dirk Gorissen
Research - Tech4Good - Flying Robots
Twitter  : https://twitter.com/dirkgor
LinkedIn: http://www.linkedin.com/in/dirkgorissen

**Comment by SebastianLopienski** [comment]
Here you go again: #162 :-)

**Comment by dgorissen** [comment]
done
