### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by matejaputic** [dgorissen/coursera-dl#164]
Failed to authenticate even though I can authenticate through the website. I made sure I have accepted the honor policy for the course, but the behavior is the same. Also tried changing my password to a shorter password, that didn't help either. I believe I am using the latest version. Is this just a never ending cat-and-mouse game with Coursera? Any help would be appreciated.

```
Coursera-dl v3.1 (html.parser)
Logging in as 'mst3k@virginia.edu'...
Traceback (most recent call last):
  File "/home/mst3k/coursera_project/venv/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
  File "/home/mst3k/coursera_project/venv/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 649, in main
    d.login(args.course_names[0])
  File "/home/mst3k/coursera_project/venv/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 168, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as mst3k@virginia.edu
```

**Comment by ctrainr** [comment]
same problem

**Comment by afedulov** [comment]
+1

**Comment by helloworldcoursera** [comment]
Same Issue - Failed to authenticate. Any ideas on what might be going wrong ?

**Comment by jungleslave** [comment]
Ditto. Please Help !

**Comment by seifer08ms** [comment]
+1!  Same problem !

**Comment by visini** [comment]
Same here, unable to download anything. Seems like they changed their login behavior very recently.

```
Coursera-dl v3.1 (html.parser)
Logging in as 'xxx@yyy.com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 649, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/site-packages/courseradownloader/courseradownloader.py", line 168, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as xxx@yyy.com
```

**Comment by paulvictor** [comment]
+1. Same problem here

**Comment by dgorissen** [comment]
This is probably because coursera changed something on their authentication side. So the coursera-dl code needs updating. Has happened a couple of times before and usually not major. I will take a look but don't have much bandwidth, so it wont be this week. So anybody able to already take a poke at the code would be much appreciated.

**Comment by HyShai** [comment]
The error is `Invalid CSRF Token`

**Comment by HyShai** [comment]
You can see the change needed to implement [here](https://github.com/sanketh95/coursera-offline/blob/master/coursera_offline.py#L161) - basically it needs another CSRF token.

 (I don't have time ATM to do it here)

**Comment by Jared314** [comment]
Oddly enough, the 2.0.2 version authenticated correctly for me. Downgrading might be a plausible workaround until the issue is resolved.

```
$ pip uninstall coursera-dl
$ pip install coursera-dl==2.0.2
```

**Comment by HyShai** [comment]
Can confirm 2.0.2 authenticates.

Thanks @Jared314

**Comment by nick-s-b** [comment]
Are there any issues with 2.0.2 branch?

**Comment by visini** [comment]
2.0.2 worked for me, thanks!

**Comment by danmbox** [comment]
Where was 2.0.2 in Git? I don't see any tags...

**Comment by nomoreidsavailable** [comment]
Confirmed!
2.0.2 worked for me as well!
Thank you!

**Comment by ghost** [comment]
2.0.2 Works well
Thanks Jared314

**Comment by danmbox** [comment]
I've tried commit ac0c411a69ebea3ffb26944b23c5a92718921007 on the mechanize branch (which seems to be version 2.0.2) but I'm still getting authentication problems

**Comment by beastman001** [comment]
Downloading epidemics-002 with Version 2.0.2. Works, but some 0 byte files.

**Comment by danmbox** [comment]
beastman001 -- well, it's on the requests branch that used to have problems and was eventually abandoned. That's why we need to fix the mechanize branch

**Comment by danmbox** [comment]
OK, for some reason ca9d3b35777534774a9777ad0fbc32e8b699da3d (2.0.2 on master) works, but ac0c411a69ebea3ffb26944b23c5a92718921007 (2.0.2 on the mechanize branch) doesn't. There's an extra 'csrftoken:' header, but even if I add that, it still doesn't work. The actual failure is that the second request returns a "400 Bad Request" error (which is not caught immediately).

**Comment by danmbox** [comment]
I've created a pull request for mechanize (#166). Seems to solve the issue.
