### ISSUE TITLE
Problem with proxy authentication

### ISSUE THREAD

**Issue by emmedema** [dgorissen/coursera-dl#17]
I am trying to use the script at work, behind a corporate proxy. 
Everything works from the network perspective (I pip-installed coursera-dl without problems) but when I try to use the script, I get this error:

File "/home/xyz/.virtualenvs/coursera/lib/python2.7/site-packages/mechanize/_urllib2_fork.py", line 1118, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error Tunnel connection failed: 407 Proxy Authentication Required>

Shouldn't urllib get the setup default proxy configurations from the system? 
Also, maybe the addition of a --proxy parameter could come handy...

**Comment by dgorissen** [comment]
Added an option (-x flag) have a try and see if it works for you.
