### ISSUE TITLE
Add an mp3 converter

### ISSUE THREAD

**Issue by 3like3beer** [dgorissen/coursera-dl#174]
One reason I download online courses video is to extract the audio track and to put them on my mp3 player.
Now the process is manual (dl + shell scripts)
Automating the process  would be a great feature (at least for me)

**Comment by danmbox** [comment]
Please don't add extraneous features (especially since the project is somewhat on life support). There are many ways to convert depending on the platform and what other software the user has installed.

**Comment by 3like3beer** [comment]
Ok, too bad you don't feel it useful, but it can indeed be achieved by other means. Thanks for the reply.
