### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by michaeljf** [dgorissen/coursera-dl#19]
Thank you for putting this together and maintaining it!

I am trying to upgrade from 1.1.11 to 1.2.1 using pip install --upgrade coursera-dl.  This is on ubuntu 12.04 LTS OS.  I am getting the following error:

Downloading/unpacking coursera-dl
  Running setup.py egg_info for package coursera-dl
    running egg_info
    writing requirements to pip-egg-info/coursera_dl.egg-info/requires.txt
    writing pip-egg-info/coursera_dl.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/coursera_dl.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/coursera_dl.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/coursera_dl.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'pip-egg-info/coursera_dl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pip-egg-info/coursera_dl.egg-info/SOURCES.txt'
```

Downloading/unpacking mechanize (from coursera-dl)
  Getting page http://pypi.python.org/simple/mechanize
  URLs to search for versions for mechanize (from coursera-dl):
- http://pypi.python.org/simple/mechanize/
  Getting page http://wwwsearch.sourceforge.net/mechanize/
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.1a.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.1a.tar.gz when looking for download links for mechanize (from coursera-dl)
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.11a.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.11a.tar.gz when looking for download links for mechanize (from coursera-dl)
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.8a.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.8a.tar.gz when looking for download links for mechanize (from coursera-dl)
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.11.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.10a.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.10a.tar.gz when looking for download links for mechanize (from coursera-dl)
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.1.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.3.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.2b.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.2b.tar.gz when looking for download links for mechanize (from coursera-dl)
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.5b.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.5b.tar.gz when looking for download links for mechanize (from coursera-dl)
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.8.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.2.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.1a.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.1a.tar.gz when looking for download links for mechanize (from coursera-dl)
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.7b.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.6b.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.6b.tar.gz when looking for download links for mechanize (from coursera-dl)
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.4b.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.4b.tar.gz when looking for download links for mechanize (from coursera-dl)
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.10.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.9.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.4.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Skipping page http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.0.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/x-gzip
  Could not fetch URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.9a.tar.gz (from http://pypi.python.org/simple/mechanize/): HTTP Error 404: Not Found
  Will skip URL http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.9a.tar.gz when looking for download links for mechanize (from coursera-dl)
  Skipping page http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.tar.gz (from http://pypi.python.org/simple/mechanize/) because of Content-Type: application/octet-stream
  Analyzing links from page http://pypi.python.org/simple/mechanize/
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.2.tar.gz#md5=22fd64c71c065619d27ea8870da6ca68 (from http://pypi.python.org/simple/mechanize/), version: 0.2.2
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.11.zip#md5=6a901ba7b96e178382e33c5b984dbaa0 (from http://pypi.python.org/simple/mechanize/), version: 0.1.11
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.4.tar.gz#md5=0c1c3cec1c6d7b5d87662a069f04eb8d (from http://pypi.python.org/simple/mechanize/), version: 0.2.4
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.0.tar.gz#md5=4fe7a892abb8f55265d94aaf0b6c275b (from http://pypi.python.org/simple/mechanize/), version: 0.2.0
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.0.zip#md5=5b1db766c474a5c8d4be8a83acf39e66 (from http://pypi.python.org/simple/mechanize/), version: 0.2.0
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.3.zip#md5=3682f4a47d9614222cf7561ecb5ab0d4 (from http://pypi.python.org/simple/mechanize/), version: 0.2.3
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.1.zip#md5=44a380d371e6f64d1503bc04c4660c8c (from http://pypi.python.org/simple/mechanize/), version: 0.2.1
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.9.zip#md5=7295d097dc2c223599265ac259d60a58 (from http://pypi.python.org/simple/mechanize/), version: 0.1.9
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.8.tar.gz#md5=858a70d518f7a677e7de512105579f8c (from http://pypi.python.org/simple/mechanize/), version: 0.1.8
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.11.tar.gz#md5=c5e89a1886e44bd7a8598b0ba47287af (from http://pypi.python.org/simple/mechanize/), version: 0.1.11
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.10.zip#md5=0b1a7bca36dbb2e45a80fbfd49de92da (from http://pypi.python.org/simple/mechanize/), version: 0.1.10
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.zip#md5=a497ad4e875f7506ffcf8ad3ada4c2fc (from http://pypi.python.org/simple/mechanize/), version: 0.2.5
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.tar.gz#md5=32657f139fc2fb75bcf193b63b8c60b2 (from http://pypi.python.org/simple/mechanize/), version: 0.2.5
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.9.tar.gz#md5=6754f9959a2d00ec028bf84db9300e87 (from http://pypi.python.org/simple/mechanize/), version: 0.1.9
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.8.zip#md5=34e4fcd2cc408d4a711e57b4723b6ff4 (from http://pypi.python.org/simple/mechanize/), version: 0.1.8
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.1.tar.gz#md5=0577e595de60f2553cd76fcf625babb7 (from http://pypi.python.org/simple/mechanize/), version: 0.2.1
    Skipping link http://pypi.python.org/packages/2.5/m/mechanize/mechanize-0.1.8-py2.5.egg#md5=c8052a21c0c743b821d42bdffbbcfc36 (from http://pypi.python.org/simple/mechanize/); unknown archive format: .egg
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.4.zip#md5=b35e514db998f3da0d19f5f838882389 (from http://pypi.python.org/simple/mechanize/), version: 0.2.4
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.3.tar.gz#md5=3a2e803cf1c7e68e172a62db1ad088a2 (from http://pypi.python.org/simple/mechanize/), version: 0.2.3
    Skipping link http://pypi.python.org/packages/2.5/m/mechanize/mechanize-0.1.9-py2.5.egg#md5=274b83d6dce58ff0fdbc4010949f874f (from http://pypi.python.org/simple/mechanize/); unknown archive format: .egg
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.1.10.tar.gz#md5=596929b51dc7fb6f39f785db5095637f (from http://pypi.python.org/simple/mechanize/), version: 0.1.10
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.2.zip#md5=7946d8c5c700e1f6670476afa2a6f6cd (from http://pypi.python.org/simple/mechanize/), version: 0.2.2
    Skipping link http://wwwsearch.sourceforge.net/mechanize/ (from http://pypi.python.org/simple/mechanize/); not a file
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.1a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.0.1a
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.11a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.0.11a
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.8a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.0.8a
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.11.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.11
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.10a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.0.10a
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.1.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.2.1
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.3.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.2.3
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.2b.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.2b
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.5b.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.5b
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.8.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.8
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.2.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.2.2
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.1a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.1a
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.7b.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.7b
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.6b.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.6b
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.4b.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.4b
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.10.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.10
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.9.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.9
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.4.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.2.4
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.2.0.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.2.0
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.0.9a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.0.9a
    Found link http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.2.5
    Found link http://wwwsearch.sourceforge.net/mechanize/src/mechanize-0.1.0a.tar.gz (from http://pypi.python.org/simple/mechanize/), version: 0.1.0a
  Analyzing links from page http://wwwsearch.sourceforge.net/mechanize/
    Skipping link http://sourceforge.net/ (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://wwwsearch.sourceforge.net/mechanize/download.html (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://wwwsearch.sourceforge.net/mechanize/support.html (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://wwwsearch.sourceforge.net/mechanize/development.html (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://wwwsearch.sourceforge.net/mechanize/#examples (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://wwwsearch.sourceforge.net/mechanize/#credits (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://wwwsearch.sourceforge.net/mechanize/#see-also (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://search.cpan.org/dist/WWW-Mechanize/ (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://www.robotstxt.org/wc/norobots.html (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://wwwsearch.sourceforge.net/mechanize/documentation.html#examples (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://search.cpan.org/dist/libwww-perl/ (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://docs.python.org/release/2.6/library/urllib2.html (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://cheeseshop.python.org/pypi?:action=display&amp;name=zope.testbrowser (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://twill.idyll.org/ (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link http://wwwsearch.sourceforge.net/mechanize/faq.html (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .html
    Skipping link http://lists.sourceforge.net/lists/listinfo/wwwsearch-general (from http://wwwsearch.sourceforge.net/mechanize/); not a file
    Skipping link mailto:jjl@pobox.com (from http://wwwsearch.sourceforge.net/mechanize/); unknown archive format: .com
  Using version 0.2.5 (newest of versions: 0.2.5, 0.2.5, 0.2.5, 0.2.4, 0.2.4, 0.2.4, 0.2.3, 0.2.3, 0.2.3, 0.2.2, 0.2.2, 0.2.2, 0.2.1, 0.2.1, 0.2.1, 0.2.0, 0.2.0, 0.2.0, 0.1.11, 0.1.11, 0.1.11, 0.1.10, 0.1.10, 0.1.10, 0.1.9, 0.1.9, 0.1.9, 0.1.8, 0.1.8, 0.1.8, 0.1.7b, 0.1.6b, 0.1.5b, 0.1.4b, 0.1.2b, 0.1.1a, 0.1.0a, 0.0.11a, 0.0.10a, 0.0.9a, 0.0.8a, 0.0.1a)
  Error <urlopen error [Errno -2] Name or service not known> while getting http://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.zip#md5=a497ad4e875f7506ffcf8ad3ada4c2fc (from http://pypi.python.org/simple/mechanize/)
  Exception:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 955, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1072, in unpack_url
    return unpack_http_url(link, location, self.download_cache, only_download)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 428, in unpack_http_url
    resp = _get_response_from_url(target_url, link)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 457, in _get_response_from_url
    resp = urlopen(target_url)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 83, in __call__
    response = urllib2.urlopen(self.get_request(url))
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
  URLError: <urlopen error [Errno -2] Name or service not known>

Thank you, Michael

**Comment by dgorissen** [comment]
This looks like pip is having trouble resolving some dependencies. Have you tried using easy_install to upgrade mechanize, or just download/install it manually (optionally removing the old version first)?
