### ISSUE TITLE
quizzes and assignments

### ISSUE THREAD

**Issue by alij** [dgorissen/coursera-dl#2]
Why is the code for quizzes and assignments commented out?

**Comment by dgorissen** [comment]
Three main reasons:
- there is no single convention for quizzes/homeworks/assignments/interview questions across courses. While the url scheme may be the same, what you get may be different
- downloading the actual quizzes/homeworks/... (and maybe the hints as well) means more automatic form filling 
- accessing the quizzes/homeworks/... like that will be recorded as an attempt, so if you are trying to do the course for real you would probably not want that

You could code up something to deal with all three points but I haven't been able to do that yet and its not a big priority for me personally. Pull requests more than welcome though :)

**Comment by alij** [comment]
Thanks for the details! The script is running great for me otherwise, so I guess I could live without having the assignments :)

**Comment by afu1979** [comment]
I will probably have a pull request for this soon. It doesn't appear to be recorded as an attempt but I have someone who audits a lot of classes beta testing right now.

**Comment by dgorissen** [comment]
Awesome thanks!

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by fsmefe** [comment]
Do you have any news on this Afu? The coursera-dl is amazing the way it is but it would be wonderful if users could also download the homeworks automatically.

**Comment by afu1979** [comment]
Sorry for the delay. I was behind on my homework from my coursera classes. I have submitted a pull request.
