### ISSUE TITLE
Specify week(s) to download

### ISSUE THREAD

**Issue by gnufz** [dgorissen/coursera-dl#21]
Would it be possible to specify the week(s) to download material for? I'm currently taking a course that is six weeks long, with content released on Monday morning each week. The download script detects that it has previously downloaded Week 1's material, but it takes a while for it figure that out. By the time I get to the last week, it will have to walk through the first five weeks before starting to download anything.

**Comment by dgorissen** [comment]
Im aware of this issue. Specifying the weeks could work though it relies on courses following a particular naming convention and I can imagine there being a couple of corner cases. Better would be to automatically keep track of what downloaded successfully and always restart from there. I have bee meaning to implement that for some time but haven't got to it as it does not annoy me enough yet :) I typically just let it run for a while.

**Comment by dgorissen** [comment]
You can now specify which weeks to download with -w
