### ISSUE TITLE
WindowsError: [Error3]

### ISSUE THREAD

**Issue by Seekeer** [dgorissen/coursera-dl#22]
Got this error while executing script:
![image](https://f.cloud.github.com/assets/2019187/161562/26c8d8a8-7793-11e2-9c4e-56c2477091de.png)
How could I fix it?

**Comment by dgorissen** [comment]
It looks like you are calling the script with "algs4part1-001/class/index" instead of just "algs4part1-001" ?

**Comment by Seekeer** [comment]
Thanks. Looks like that solved the issue. Sorry for stupidness and thanks for script.
