### ISSUE TITLE
debugger

### ISSUE THREAD

**Issue by archit90** [dgorissen/coursera-dl#23]
Hi,
I would like to know what IDE u used to create the script.  
I am able to understand the code to some extent but not able to understand the library functions used.
So if you could tell what IDE to use to understand/debug the code would be very helpful

Thanks!

**Comment by dgorissen** [comment]
Vim :) http://en.wikipedia.org/wiki/Vim_(text_editor) So no fancy IDE/debugger Im afraid. There are a number of "real" ide's but I am by no means familiar with all of them. The only other one I have really used is pydev.org and it is easy enough to get going with.
