### ISSUE TITLE
Doesn't recognize the directory in Mac for downloading!

### ISSUE THREAD

**Issue by danzean** [dgorissen/coursera-dl#26]
I created a directory called 'test' and then ran the following on the command line
'coursera-dl -u myusername -p mypassword -d /test/courses/ algo-2012-001' 

 The script seems to be having difficulty in finding the 'test' folder I created to download the course contents. Where should I be creating the directory? at the root? should I also be creating a directory 'courses' underneath the 'test' directory? I am a total newbie and not too familiar with Mac. I am on Mac OS 10.8,2. Please help!!
## Here is the error message I got:

Warning: lxml not available, falling back to built-in 'html.parser' (see -q option), this may cause problems on Python < 2.7.3
HTML parser set to html.parser
- Authenticating as jpabbath@yahoo.com...
- Collecting downloadable content from http://class.coursera.org/algo-2012-001/lecture/index
- Got all downloadable content for algo-2012-001
  Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 8, in <module>
    load_entry_point('coursera-dl==1.2.1', 'console_scripts', 'coursera-dl')()
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 472, in main
    d.download_course(cn,dest_dir=args.dest_dir)
  File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 201, in download_course
    os.mkdir(course_dir)
  OSError: [Errno 2] No such file or directory: '/test/courses/algo-2012-001'

**Comment by dgorissen** [comment]
I suspect a permission problem as you created test in the root (note the leading slash in /test/..). Don't do this, use a directory relative to your home directory (e.g., /Users/foobar/test) instead.
