### ISSUE TITLE
Coursera-dl not working with update

### ISSUE THREAD

**Issue by systah** [dgorissen/coursera-dl#29]
I performed an upgrade and installed the additional dependencies. Now I'm recieving this error: 
C:\Python27\Scripts>coursera-dl --quiz -u xxxx -p xxxx -d c:_
Downloads\classes\test\
Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\setuptools-0.6c12dev_r88846-py2.7.egg\pkg_
resources.py", line 2603, in <module>
  File "C:\Python27\lib\site-packages\setuptools-0.6c12dev_r88846-py2.7.egg\pkg_
resources.py", line 666, in require
  File "C:\Python27\lib\site-packages\setuptools-0.6c12dev_r88846-py2.7.egg\pkg_
resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: cssselect

I thought it was setup tools so updated ez_setup, still occurs. I've no idea what's going on. Any help???

Thanks :>

**Comment by systah** [comment]
Update: I reinstalled everything fresh and am still receiving the error / issue above
during install the error: 

copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_x
slt1.xsl -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-
xslt1

copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt ->
build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1

running build_ext

building 'lxml.etree' extension

error: Unable to find vcvarsall.bat

---

Command c:\Python27\python.exe -c "import setuptools;**file**='c:\users\meegan
~1\appdata\local\temp\pip-build-MeegansLair\lxml\setup.py';exec(compile(op
en(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record
c:\users\meegan~1\appdata\local\temp\pip-ekoyuw-record\install-record.txt --sing
le-version-externally-managed failed with error code 1 in c:\users\meegan~1\appd
ata\local\temp\pip-build-MeegansLair\lxml

**Comment by olegafx** [comment]
Same here.

**Comment by systah** [comment]
Sorry it's happening to you but I'm glad I'm not the only also :(

**Comment by dgorissen** [comment]
Those are errors are are to do with your compiler setup. However, ignore them as I found a far simpler solution and removed all the pyqt dependencies again. Please update and try again.
