### ISSUE TITLE
Correct representation of video length

### ISSUE THREAD

**Issue by jcea** [dgorissen/coursera-dl#33]
While downloading the video, I see messages like:

"- Downloading resources for 1.4 XXXX (1511)"

After a while I realized that "(1511)" really represent duration of the video. A more appropiate representation would be "(15:11)". That is, adding a colon.

Thanks for this useful script!.

**Comment by olegafx** [comment]
It's name of a file or folder. You can't name a file/folder with ":" character. What's the difference between "1511" and "15:11" on the output? It's just an additional work for author and your computer :)

**Comment by jcea** [comment]
Well, you actually can use ":" in Unix :-). I know this a cosmetic request, though.

**Comment by jcea** [comment]
Feel free to close if you feel like it. But cosmetics can be important.

**Comment by dgorissen** [comment]
Yeah, Im aware of this issue. You could allow ":" in filenames on unix but
what if people start accessing files across different os's (ie, via a
shared drive)? Cleanest is probably to do a regex match on the class titles
and replacing the ":" by something valid (hyphen?). Should be quite easy to
do, will merge it if you create a pull request :)
