### ISSUE TITLE
Use a .netrc file to store the username and password?

### ISSUE THREAD

**Issue by suvil** [dgorissen/coursera-dl#34]
Instead of typing in the username and password everytime we launch the script can't we use a .netrc file to store our account credentials and call them on need?

Example as in this case - https://github.com/jplehmann/coursera

Thanks!

**Comment by dgorissen** [comment]
Good idea, will add it to my todo list, patches welcome :)

**Comment by paulproteus** [comment]
Just to clarify the request, for anyone else who comes along to implement this:

The functionality would be that it would look for a file called .netrc in your home directory. If it had a line like the following (with no leading whitespace):

```
machine coursera-dl login USERNAME password PASSWORD
```

then the program would use the username USERNAME and password PASSWORD as if they were passed on the command line.
