### ISSUE TITLE
Can we reduce cosmetic changes to file/folder names

### ISSUE THREAD

**Issue by rodch-us** [dgorissen/coursera-dl#41]
I have 3 sets of files for  course scientificthinking. One without time stamp, one with time stamps and (today I upgraded courseradownload.py) and one with time stamp with character '-' in between. These are the same files but different names. It is wastage of resources, both mine and as well coursera, to download these files over and over again.
Dgorissen your project has now life of its own and anything that is not really essential like time stamp on file/folders could be deferred or put in another project. Or maybe you can strengthen the check on existence of file before downloading. It will save lot of resources. 
Thanks Rod.

**Comment by dgorissen** [comment]
I understand the annoyance as I have the same problem wrt to duplicate
entries, but its only a problem for in-progress courses. I always try to
avoid such changes though where possible.

Its a balance of on the one hand accommodating feature/change requests I
get sent and on the other hand minimizing impact on existing users.
However, given usage of the script has grown I will start maintaining a
proper changelog so users can always check this before upgrading. That
should appear in the next release.

Cheers
Dirk

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu
