### ISSUE TITLE
issue(s) downloading some classes

### ISSUE THREAD

**Issue by dpastoor** [dgorissen/coursera-dl#50]
Get following error message only downloading some courses

courses noticed problem:

econ1scientists-2012-001 introstats-001 

courses tried in same session that successfully downloaded:

GTG-2013-001 macroeconomics-2012-001

error message:

Course 1 of 1
*collecting downloadable content from https://class.coursera.org/introstats-001/lecture/index
Traceback (most recent call last):
File “c:\Python27\scripts\coursera-dl-script.py”, line 9, in <module>
load_entry_point(’coursera-dl==1.4.8’, ‘console_scripts’, ‘coursera-dl’)Q
Fi le “c:\Python27\lib\site-packages\courseradownloader\courseradownloader.py”,
line 598, in main
d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
Fi le “c:\Python27\lib\site-packages\courseradownloader\courseradownloader.py”,
line 301, in download_course
(weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
Fi le “c:\Python27\lib\site—packages\courseradownloader\courseradownloader.py”,
line 186, in get_downloadable_content
hrefs = classResources.findAll(’a’)
AttributeError: ‘NoneType’ object has no attribute ‘findAll’

**Comment by altimerk** [comment]
Hi, this error appears with lxml as default parser. Try use html.parser instead

**Comment by dpastoor** [comment]
Sorry for my naiveity - what would the best way of forcing the HTML parser
by default. Can this be done in the script?

Thanks!

**Comment by altimerk** [comment]
You can use -q option for script:
coursera-dl -u username -p password -d directory -q html.parser <course>

**Comment by dgorissen** [comment]
assuming fixed like #49 . Reopen if not.
