### ISSUE TITLE
Error while downloading only the below course. Works fine for other courses.

### ISSUE THREAD

**Issue by nagnag** [dgorissen/coursera-dl#52]
C:\Coursera>coursera-dl -u nagesh.nagara@gmail.com -p xxxxxxxx hwswinterfac
e-001
 Warning: lxml not available, falling back to built-in 'html.parser' (see -q opt
ion), this may cause problems on Python < 2.7.3
Coursera-dl v1.4.7 (html.parser)

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/hwswinterface-
  001/lecture/index
  Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 8, in <module>
    load_entry_point('coursera-dl==1.4.7', 'console_scripts', 'coursera-dl')()
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
  line 546, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
  line 296, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py",
  line 208, in get_downloadable_content
    bb = BeautifulSoup(p,self.parser)
  NameError: global name 'p' is not defined

**Comment by togaurav** [comment]
Hey 
From stack-trace it looks like you are using Coursera-dl v1.4.7,
try to update the coursera-dl script, the latest one is 1.4.8, 
hopefully it will resolve the issue..

**Comment by dgorissen** [comment]
assuming fixed. Reopen if problem persists.

**Comment by dgorissen** [comment]
assuming fixed. Reopen if problem persists.
