### ISSUE TITLE
exception when trying to create long directories

### ISSUE THREAD

**Issue by rodch-us** [dgorissen/coursera-dl#56]
I am trying new script with modifications for long filenames. I am getting following error with course "writing 2" and the error is as following:

 File "courseradownloader.py", line 650, in <module>
   main()
 File "courseradownloader_filename.py", line 647, in main
   d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
 File "courseradownloader_filename.py", line 374, in download_course
   os.makedirs(clsdir)
 File "E:\Python27\lib\os.py", line 157, in makedirs
   mkdir(name, mode)
WindowsError: [Error 206] The filename or extension is too long: 'c:\Cou\writing
-001\07 - Unit 3 Analyzing Rhetorically\07 - Core Analyzing Text [0448] Avail
ble as streaming content at httpgo.osu.eduanalyzingtext. Please point your web
rowser to that URL or download a text transcript using the icon link at right -
'

**Comment by dgorissen** [comment]
Mmm, yeah I feared that would come up at some point. There is no trivial
fix here as you need to do a little looking ahead to avoid having things
that belong together end up in different directories. I will try to fix
this as soon as I find some time.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by dgorissen** [comment]
Can you have another try with the current master. You may still have a similar error so please past the full output. Unfortunately I cannot try myself as the writing2 course has ended.
