### ISSUE TITLE
One mp4 download failed

### ISSUE THREAD

**Issue by akushsky** [dgorissen/coursera-dl#57]
Failed to download url https://class.coursera.org/behavioralecon-001/lecture/download.mp4?lecture_id=135 to /home/0common/Coursera/behavioralecon-001/09 - Office Hours/01 - Week 1 Office Hours/9 - 1 - Week 1 Office Hours.mp4: out of memory

Yes, I have less RAM on my NAS, but a lot of HDD. What can I do with it?

**Comment by dgorissen** [comment]
Not much coursera-dl can do anything about Im afraid. Mechanize is used to
do the actual downloading and Im not sure what actually happens under the
hood. It might be possible to reduce the memory footprint by using smaller
buffers or so but I dont have the time currently to really dive into the
nuts and bolts of it. If its just one file a workaround is just to download
that one manually on a different machine.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by akushsky** [comment]
So, I do that yesterday)) It's okey, thank you)
