### ISSUE TITLE
Download halts on Windows

### ISSUE THREAD

**Issue by lsoliveira459** [dgorissen/coursera-dl#63]
The download stops arbitrarily on Windows. The first time it happened it had just finished downloading a course content and should start downloading the next course. The second time it was downloading course's class and wouldn't start the next one. Third time was the same as second.

The first time I restarted the program but I noticed a simple crtl-c (SIGINT) would make the program continue.

This is really bad specially for those who want to let it downloading through the night.

PS: I'm using pip's version of coursera-dl (v1.4.10).

**Comment by dgorissen** [comment]
mmm I have had no such issues here. Are you sure it is not a flaky network
connection?

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by lsoliveira459** [comment]
Define flaky. My network has a steady connection, even though it's slow (~400 kbps = 50 KBps). Something I forgot to mention though: I'm under Windows 8 (Pro, but this shouldn't make a difference)... I'm not downloading anything else in this network nor am doing any heavy computation on this PC.

Here's a screenshot, for the unbelivers.
![untitled](https://f.cloud.github.com/assets/2242083/845026/60ab0330-f3de-11e2-834d-33e9e35cc041.png)

This problem happened already about 10 times in a period of 3 or 4 days. On this specific time (the one on the screenshot) and a few others, I had to ctrl-alt-del the program or it wouldn't download again. As I said before, the behavior is a little bit arbitrary/random.

During the night though, the program seems to not halt. Or else, it somehow recovers by itself. I'm not sure if any of those things make sense.

I can think of a few possibilities:
1. My Windows is screwed
2. Windows 8 changed whatever network library Python is using
3. Coursera is timeouting my connection
4. The program has some very well-hidden bug

I don't believe that neither my Windows is screwed nor Coursera is timeouting my connection. If so, I'd be having a lot more problems. That leaves us with a problem between Python and Windows or in coursera-dl. I remember Python behaves differently on Linux/Unix and Windows, specially regarding files/streams, so it might be a combination of the two.

I'll try to work on this next week too, after finals.

**Comment by lsoliveira459** [comment]
Well... Analyzing the code, the only strange thing I found was inside mechanize. I'm changing it for Requests to see if this problem goes away.

**Comment by dgorissen** [comment]
Cool, thanks. Let me know if you find something. I have not had any issues
myself or had anybody else report any.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by lsoliveira459** [comment]
Have you considered multithreading (in python's case Multiprocessing)? One process to populate a list of urls and another to download. And how about an update feature, where the user would only say --update and the program would id. the classes and download the new files.

Where do I propose those features?

**Comment by dgorissen** [comment]
Yes on both counts, would be great features to have. Unfortunately though
currently out of my time-budget. Feel free to create github issues for both
so the can be tracked. But I will be unable to get to them in the near
term. Happy to merge patches though :)

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu
