### ISSUE TITLE
This week's lectures from casebasedbiostat-001 are not getting downloaded

### ISSUE THREAD

**Issue by rpolavar** [dgorissen/coursera-dl#64]
ar All: I am able to download the lectures from the previous two weeks.  Not this week.  Thank you for your help. Ramana

**Comment by dgorissen** [comment]
still an issue?

**Comment by rpolavar** [comment]
Hi Dirk:

Yes.  The problem continues.  I think that the problem is related to
long file name.  Thank you.

Best regards,

Ramana

**Comment by dgorissen** [comment]
have you tried running with --trim-path?

**Comment by rpolavar** [comment]
Hi Dirk:

Thank you for the suggestion but no luck:
C:\Users\rpolavar>coursera-dl -u sriramana@gmail.com -p  -d c:/coursera -
-trim-path casebasedbiostat-001
Coursera-dl v1.4.10 (html.parser)
Maximum path length set to 257
Logging in as 'sriramana@gmail.com'...

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/casebasedbiost
  at-001/lecture/index
- Got all downloadable content for casebasedbiostat-001
- casebasedbiostat-001 will be downloaded to c:\coursera\casebasedbiostat-001
  - Downloading lecture/syllabus pages
  - Module 1 What common background understanding do I need to get started in imp
    roving my ability to critically and quantitatively reason about health questions
  - Downloading resources for 1.1. The Scientific Method (19-23)
    - "ZegerLecture1.pdf" already exists, skipping
      Trimmed path name "c:\coursera\casebasedbiostat-001\01 - Module 1 What common b
      ackground understanding do I need to get started in improving my ability to crit
      ically and quantitatively reason about health questions\01 - 1.1. The Scientific
      Method (19-23)\1 - 1 - 1.1. The Scientific Method (1923).txt" to "c:\coursera\c
      asebasedbiostat-001\01 - Module 1 What common background understanding do I need
      to get started in improving my ability to critically and quantitatively reason
      about health questions\01 - 1.1. The Scientific Method (19-23)\1 - 1 - 1.1. The
      .txt" to fit required length (257)
      Trimmed path name "c:\coursera\casebasedbiostat-001\01 - Module 1 What common b
      ackground understanding do I need to get started in improving my ability to crit
      ically and quantitatively reason about health questions\01 - 1.1. The Scientific
      Method (19-23)\1 - 1 - 1.1. The Scientific Method (1923).srt" to "c:\coursera\c
      asebasedbiostat-001\01 - Module 1 What common background understanding do I need
      to get started in improving my ability to critically and quantitatively reason
      about health questions\01 - 1.1. The Scientific Method (19-23)\1 - 1 - 1.1. The
      .srt" to fit required length (257)
      Trimmed path name "c:\coursera\casebasedbiostat-001\01 - Module 1 What common b
      ackground understanding do I need to get started in improving my ability to crit
      ically and quantitatively reason about health questions\01 - 1.1. The Scientific
      Method (19-23)\1 - 1 - 1.1. The Scientific Method (1923).mp4" to "c:\coursera\c
      asebasedbiostat-001\01 - Module 1 What common background understanding do I need
      to get started in improving my ability to critically and quantitatively reason
      about health questions\01 - 1.1. The Scientific Method (19-23)\1 - 1 - 1.1. The
      .mp4" to fit required length (257)
  - "1 - 1 - 1.1. The Scientific Method (1923).mp4" already exists, skipping
  - Downloading resources for 1.2. On Cause (9-34)
    - "ZegerLecture2.pdf" already exists, skipping
    - "1 - 2 - 1.2. On Cause (934).mp4" already exists, skipping
  - Downloading resources for 1.3. On Probability (37-37)
    - "ZegerLecture3.pdf" already exists, skipping
      Trimmed path name "c:\coursera\casebasedbiostat-001\01 - Module 1 What common b
      ackground understanding do I need to get started in improving my ability to crit
      ically and quantitatively reason about health questions\03 - 1.3. On Probability
      (37-37)\1 - 3 - 1.3. On Probability (3737).txt" to "c:\coursera\casebasedbiosta
      t-001\01 - Module 1 What common background understanding do I need to get starte
      d in improving my ability to critically and quantitatively reason about health q
      uestions\03 - 1.3. On Probability (37-37)\1 - 3 - 1.3. On Probabil.txt" to fit r
      equired length (257)
      Trimmed path name "c:\coursera\casebasedbiostat-001\01 - Module 1 What common b
      ackground understanding do I need to get started in improving my ability to crit
      ically and quantitatively reason about health questions\03 - 1.3. On Probability
      (37-37)\1 - 3 - 1.3. On Probability (3737).srt" to "c:\coursera\casebasedbiosta
      t-001\01 - Module 1 What common background understanding do I need to get starte
      d in improving my ability to critically and quantitatively reason about health q
      uestions\03 - 1.3. On Probability (37-37)\1 - 3 - 1.3. On Probabil.srt" to fit r
      equired length (257)
      Trimmed path name "c:\coursera\casebasedbiostat-001\01 - Module 1 What common b
      ackground understanding do I need to get started in improving my ability to crit
      ically and quantitatively reason about health questions\03 - 1.3. On Probability
      (37-37)\1 - 3 - 1.3. On Probability (3737).mp4" to "c:\coursera\casebasedbiosta
      t-001\01 - Module 1 What common background understanding do I need to get starte
      d in improving my ability to critically and quantitatively reason about health q
      uestions\03 - 1.3. On Probability (37-37)\1 - 3 - 1.3. On Probabil.mp4" to fit r
      equired length (257)
  - "1 - 3 - 1.3. On Probability (3737).mp4" already exists, skipping
    Traceback (most recent call last):
    File "C:\Anaconda\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.4.10', 'console_scripts', 'coursera-dl')()
    File "C:\Anaconda\lib\site-packages\courseradownloader\courseradownloader.py",
    line 637, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
    File "C:\Anaconda\lib\site-packages\courseradownloader\courseradownloader.py",
    line 375, in download_course
    os.makedirs(clsdir)
    File "C:\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
    WindowsError: [Error 206] The filename or extension is too long: 'c:\coursera\
    casebasedbiostat-001\01 - Module 1 What common background understanding do I ne
    ed to get started in improving my ability to critically and quantitatively reaso
    n about health questions\04 - 1.4A Probability Distributions Mean  Median (8-54
    )'

C:\Users\rpolavar>

Talk to you soon.

Best regards,

Ramana

**Comment by dgorissen** [comment]
mmm maybe 257 could still be too high a bound in some cases. Try setting max_path_len to 240 or so on line 684 of courseradownloader.py. Then rerun with --trim-path and see what happens.

**Comment by dgorissen** [comment]
Does that change fix it for you?

**Comment by rpolavar** [comment]
Unfortunately, no, it did not fix it.  It was complaining that it
could not trim the path.  For now, I found a Perl script that could
download all the lectures.  This script does not organize the lectures
and the other related files into folders.  But, it does the trick for
me.  I shall get back to your program once this course is done.  Thank
you.

Regards,

Ramana

**Comment by RickMeasham** [comment]
I'm having the same problem, but this is likely due to me downloading on a VirtualBox guest to a shared folder on the Host (Windows). The actual path is a lot longer than the downloader has access to.

I wonder if you could create a '--shortfilename' option that rather than save:

```
 /win/coursera/socialpsychology-001/04 - WEEK 4 Group Behavior The Good, Bad, and Ugly/06 - Lecture 4.3 The Minimal Group From Dots to Discrimination in 60 Seconds/4 - 6 - Lecture 4.3 The Minimal Group From Dots to Discrimination in 60 Seconds.txt
```

it would save:

```
 /win/coursera/socialpsychology-001/04/06/Lecture 4.3.txt
```

And possibly put the full names into a TOC.txt

**Comment by dgorissen** [comment]
Confirmed & good suggestion. Will have a look and fix this.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by dgorissen** [comment]
In cleaning up the code I changed the current hack to fix this. Still a hack but should crash less often. Could you test with the master branch and see if it all runs ok for you. I havent been able to test in depth yet as Im travelling so report any issues.
