### ISSUE TITLE
Couldn't download the forum material

### ISSUE THREAD

**Issue by Wallace-Wang** [dgorissen/coursera-dl#65]
Whenever a forum is encountered, it shows  " - failed:  https://d396qusza40orc.cloudfront.net/usefulgenetics/forum%3Alist
%3Fforum_id%3D7 HTTP Error 403: Forbidden". 

Forum can be very valuable resources in Coursera courses. Can you tell me if there is a way to do it?

**Comment by dgorissen** [comment]
This is when the forum is linked to as one of the class resources. Unfortunately I dont have a solution or the time to look at this in depth. Happy to integrate a fix if you find one though.
