### ISSUE TITLE
Careful about being prosecuted

### ISSUE THREAD

**Issue by samrocketman** [dgorissen/coursera-dl#68]

**Comment by samrocketman** [comment]
Darn the mobile interface stinks I'll update what I mean.

**Comment by samrocketman** [comment]
https://www.coursera.org/about/terms

According to the ToS accessing content via automated means is a violation.  See Aaron Swartz case.  11 of his 13 felony charges came from violating the ToS of an academic service.  By using the site you agree to be legally bounded.  Sickening, I know.  But that's the reality we live in.  Be sure to complain to your congress members because laws about digital life are only becoming more dangerous.

**Comment by taintedzodiac** [comment]
Terms clearly say: " You may download material from the Sites only for your own personal, non-commercial use."

As long as you're not reselling or redistributing, the usage of this script clearly falls under downloading for personal use.

**Comment by dgorissen** [comment]
That was my interpretation as well. Also part of the reason the script does not automatically accept the honour code.

**Comment by samrocketman** [comment]
Actually, you're wrong.  They say the following is a violation listed under Rules for Online Conduct:

> (c) use any high-volume, automated or electronic means to access the Sites (including without limitation, robots, spiders, scripts or web-scraping tools);

I would consider this a script or high-volume automated means to access the site.  Even if you are keeping it for your own person.  I just thought I'd make you aware of the issue and potential consequences.  See the Aaron Swartz case for the scary version of the outcome.  Do with it what you will.
