### ISSUE TITLE
Cont. issue#49, v1.4.10, html parser, Error: "Warning: no downloadable content found for <several courses>"

### ISSUE THREAD

**Issue by SantiagoG** [dgorissen/coursera-dl#69]
Hello Dirk,

First, thank you for this script and all the updates and your work into it in general. 
I've been using it without any problems using Homebrew's python -which also includes pip- but since today I keep getting error message above even though using html parser.

Thanks!

**Comment by HyShai** [comment]
Same issue here. Trying to download - programdesign-001 - and getting " Warning: no downloadable content found for programdesign-001, did you accept the honour code?" (i had accepted already).

**Comment by SantiagoG** [comment]
Yep, that is not the problem. I thought that it was because I was working with courses that have ended -even though the material was still open- but that is also not the problem.

**Comment by maitreyak** [comment]
Same issue. I tried changing the default parser (lxml,html5lib) yet not luck.

**Comment by bhrgunatha** [comment]
I get this for all 4 of my current courses.
I'm using python 2.7.5 / beautiful soup 4.3.1 / mechanize 0.2.5
Not sure if it's relevant, but I tried stepping through the code - in the BeautifulSoup section (elelment.py) the in find_all I looked at all the objects returned when navigating the video index page.
I found these - just before the find_all method returned an empty list of found objects.

<div id="coursera-loading-nojs" style="text-align:center; margin-bottom:10px;display:none;">Please use a <a href="/browsers">modern browser </a> with JavaScript enabled to use Coursera.</div>

<div><span id="coursera-loading-js" style="display: none; padding-left:45%">loading   <img src="https://d2wvvaown1ul17.cloudfront.net/site-static/images/icons/loading.gif"/></span></div>

<noscript><div style="text-align:center; margin-bottom:10px;">Please use a <a href="/browsers">modern browser </a> with JavaScript enabled to use Coursera.</div></noscript>

Seems its a problem with the way coursera uses javascript.

Why do others not have this problem? Won't it be the same for everyone?

**Comment by bhrgunatha** [comment]
Sorry formatting of html strings

```
<div id="coursera-loading-nojs" style="text-align:center; margin-bottom:10px;display:none;">Please use a <a href="/browsers">modern browser </a> with JavaScript enabled to use Coursera.</div>

<div><span id="coursera-loading-js" style="display: none; padding-left:45%">loading   <img src="https://d2wvvaown1ul17.cloudfront.net/site-static/images/icons/loading.gif"/></span></div>

<noscript><div style="text-align:center; margin-bottom:10px;">Please use a <a href="/browsers">modern browser </a> with JavaScript enabled to use Coursera.</div></noscript>
```

**Comment by stephen-andrew-lynch** [comment]
Same problem. Using the same versions as bhrgunatha.

**Comment by dgorissen** [comment]
Confirmed. Will look into it tonight and/or tomorrow. Any further information/debug output is always helpful.

**Comment by bhrgunatha** [comment]
Sorry I've gone about as far as I can.
I tried lxml and html5lib for the parser also with no luck.
I did read that mechanize doesn't support javascript and the only other suggestion I could find were to use a full-fledged browser like [webkit](http://webscraping.com/blog/Scraping-JavaScript-webpages-with-webkit/) or [selenium](http://stackoverflow.com/questions/9458569/scraping-ajax-with-python) instead of mechanize.

**Comment by dgorissen** [comment]
Coursera changed their authentication details. Updated the code, seems to work for me. Test with the master branch, if you still have issues reopen.

**Comment by sunwooz** [comment]
How do I update my coursera-dl install to the master branch?  I tried doing pip install coursera-dl --upgrade, but it's saying all requirements are up to date?

**Comment by dgorissen** [comment]
You need to checkout the repo using git. See the github docs (
https://help.github.com/articles/set-up-git). If I get another confirmation
that it works (or I get to my other machine) I will update the package in
on pypi (so you can upgrade with pip)

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by maitreyak** [comment]
Works well. Thank you. 
I cloned the repo and ran:
python coursera-dl/courseradownloader/courseradownloader.py  -u username -p password -d destDir classname

Just finished downloading the entire course.
OS:Ubuntu 64

**Comment by jaskerr** [comment]
Works. Followed @maitreyak suggestion.
Thanks.

**Comment by sunwooz** [comment]
Did the same and it worked.

Thanks a lot! Love this script.

**Comment by bhrgunatha** [comment]
Yes - the fix is working. I suck at debugging :(
Thanks for your quick action and a great and useful tool.
