### ISSUE TITLE
Option to compress course after downloading?

### ISSUE THREAD

**Issue by jackmaney** [dgorissen/coursera-dl#70]
It would be nice to have, say `--gz name_of_tarball.tar.gz` and perhaps `--zip name_of_zip.zip` flags to compress the entire course folder after the download is complete, so that the courses can be compressed for relatively easy long term storage.

My Python-fu isn't strong, but I can try to tack this feature on.

**Comment by dgorissen** [comment]
Happy to accept the patch :) Should be easy to do with the zipfile library. I would make the filename optional, defaulting to the class name + .zip or similar.

**Comment by jackmaney** [comment]
After getting a bit of sleep, I realized that not a whole lot of space would be saved by tarballing the course directories, since MP4 files are already compressed. However, it would still be handy for storing courses in a single file instead of a tree of directories.

I'll add the feature this weekend.

**Comment by jackmaney** [comment]
I had some stuff come up this weekend, but I'm testing a patch now (given the size of the courses, the speed of iteration is slower than I'd like).
