### ISSUE TITLE
Cant download old courses

### ISSUE THREAD

**Issue by ankitml** [dgorissen/coursera-dl#72]
eg. with https://class.coursera.org/progfun-2012-001/lecture/index

even after accepting honor code, I get exception,

" Warning: no downloadable content found for progfun-2012-001, did you accept the honour code?
"

**Comment by seanhandley** [comment]
I get the same problem with https://class.coursera.org/intropsych-001

**Comment by seanhandley** [comment]
This is a duplicate of #71

**Comment by dgorissen** [comment]
duplicate of #69
