### ISSUE TITLE
no downloadable content for 'datasci-001' while using html.parser

### ISSUE THREAD

**Issue by geertbrit** [dgorissen/coursera-dl#74]
HI I've seen #50 with the hint to explicitly use `html.parser` when getting 'no downloadable content found for xxx'. 

I'm doing that for `datasci-001` but I'm still getting this error. Not sure what's up. 
Using following command: 

coursera-dl -u email@address -p passhere -q html.parser datasci-001

**Comment by dgorissen** [comment]
Fixed in master. Dup of #69

**Comment by geertbrit** [comment]
possible this wasn't available through pip yet? (installed today)

**Comment by dgorissen** [comment]
Pip was not updated yet, is now.

**Comment by geertbrit** [comment]
tested. Cheers
