### ISSUE TITLE
cant download lectures comnetworks-002

### ISSUE THREAD

**Issue by shagy234** [dgorissen/coursera-dl#75]
i just installed the script, and i cant download the lectures of this course.
i accepted honour code.
i have python 2.7.3
coursera-dl requirements are up to date.

any ideas?

ramiro@server:~$ coursera-dl -u xxx@hotmail.com -p pass -d /home/ramiro/curso comnetworks-002
 Warning: built-in 'html.parser' may cause problems on Python < 2.7.3
Coursera-dl v1.4.10 (html.parser)
Logging in as 'xxx@hotmail.com'...

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/comnetworks-002/lecture/index
  Warning: no downloadable content found for comnetworks-002, did you accept the honour code?

ramiro@phenom:~$ python
Python 2.7.3 (default, Apr 10 2013, 06:20:15)

ramiro@phenom:~$ sudo pip install coursera-dl --upgrade
Requirement already up-to-date: coursera-dl in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from coursera-dl)
Requirement already up-to-date: mechanize in /usr/local/lib/python2.7/dist-packages (from coursera-dl)
Requirement already up-to-date: argparse in /usr/lib/python2.7 (from coursera-dl)
Cleaning up...

**Comment by dgorissen** [comment]
Please update to the latest version.
