### ISSUE TITLE
Seems it stopped working 

### ISSUE THREAD

**Issue by amacgregor** [dgorissen/coursera-dl#76]
I keep getting this error 

Course 1 of 2
- Collecting downloadable content from https://class.coursera.org/programming2-001/lecture/index
  Warning: no downloadable content found for programming2-001, did you accept the honour code?

Course 2 of 2
- Collecting downloadable content from https://class.coursera.org/mosfet-001/lecture/index
  Warning: no downloadable content found for mosfet-001, did you accept the honour code?

I have verified that the honor code was accepted and that the page is available, I'm guessing the html parser is failing maybe the course html code changed?

**Comment by dgorissen** [comment]
Please update to the latest version.
