### ISSUE TITLE
File type based folder structure

### ISSUE THREAD

**Issue by ayberk** [dgorissen/coursera-dl#77]
It would be nice to download the contents into folders arranged by file type. That would be handy when, for example, you want to go through pdf files for reviewing the content. 

File names make it easy to understand which file belongs to which week, so it should not be a problem.

**Comment by dgorissen** [comment]
Im not sure I see the usefulness for this. As soon as you drop to file level you lose all context as to which file belongs to which class. There is the potential issue of duplicate files as well.
