### ISSUE TITLE
Failed to authenticate as...

### ISSUE THREAD

**Issue by carlosror** [dgorissen/coursera-dl#81]
Hi, thanks for the hard work! I used the script fine on Saturday and downloaded 2 of the courses I took. As of yeterday (Sunday) it's telling me it failed to auttenticate me, it's raising an exception on line 113 of coursedownloader.py:

Exception: Failed to authenticate as myUsername

I hope it's some silly mistake I am making. I am not doing anything differently from last Saturday, I don't think. What else can I try to troubleshoot? Thank you.

**Comment by dreyescat** [comment]
What did you use as username? Try using your email address instead. Don't know if Coursera has restricted the authentication to use only the email.

**Comment by ghost** [comment]
It was always e-mails right? no usernames were allowed by default I'd reckon.

**Comment by carlosror** [comment]
coursera -u myEmail -p myPassword -d pathToDisk courseName

Same as I did on Saturday, not sure what I am doing wrong now...:(

If I don't include -p myPassword, it prompts me for the password and then it rejects me again after entering it.

**Comment by carlosror** [comment]
Also in the browser logged out of Coursera and back in using my email and password.

**Comment by dreyescat** [comment]
I must have confused my Coursera with my bitbucket account authentication. Bitbucket allows both strings as usernames, username and email ;). Sorry, my fault.

BTW, I have just tried to download one of my courses and it is working smoothly.

**Comment by ghost** [comment]
@carlosror are you using windows and have you installed this script?? or do you is using your command prompt like you first cd to the directory and then run === python courseradownloader.py <args>  ?? and are you sure your using the latest commit because commit e6e7906f0628778eb256b287ea567b3e1c1f63e9 seemed to fix those errors

**Comment by carlosror** [comment]
Great! :) I thought maybe Coursera had blocked it somehow.

So you type coursera-dl -u yourEmail -p yourPwd -d path courseName?

**Comment by carlosror** [comment]
Yes using Windows and I open command prompt and type:

coursera-dl -u myEmail -p myPassword -d pathToDisk courseName

**Comment by ghost** [comment]
yeah, if you have installed the script

**Comment by carlosror** [comment]
Yes I installed it and ran it ok  a few days ago...O well..

**Comment by dreyescat** [comment]
Do you use Firefox? If so, could you please run the script without Firefox running? Maybe the browser is interfering the cookies saved by the script. It sounds weird, but if it worked before maybe it is another program that interferes.

**Comment by carlosror** [comment]
You are a genius! I closed Firefox, re-started the Command Prompt, and that did it! THANK YOU.

**Comment by dreyescat** [comment]
Glad it helped!

**Comment by carlosror** [comment]
Solved by closing Firefox and re-starting Command Prompt, per dreyescat's suggestion. :-)
