### ISSUE TITLE
Failed to authenticate since about a week

### ISSUE THREAD

**Issue by colablikje** [dgorissen/coursera-dl#87]
The new login process (https://www.facebook.com/Coursera/posts/439625136155480) seems to give trouble to the script. Indeed, I have not been able to use coursera-dl to download material since several days now (a week or so?), I only receive an authentication error (and yes, my username and password and entirely correct, and I can use them to login to my coursera courses manually). It seems that coursera-dl does not work (yet?) with Coursera's new login process.
Is there any way you can look into this and get this working again? 

This the error message:

c:\Python27\Scripts>coursera-dl -d f:\coursera animalbehav-001
Coursera-dl v1.4.8 (lxml)
Credentials found in .netrc file
Logging in as 'XXXX@gmail.com'...
Traceback (most recent call last):
  File "c:\Python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "c:\Python27\lib\site-packages\coursera_dl-1.4.8-py2.7.egg\courseradownloader\courseradownloader.py", line 592, in main
    d.login(args.course_names[0])
  File "c:\Python27\lib\site-packages\coursera_dl-1.4.8-py2.7.egg\courseradownloader\courseradownloader.py", line 111, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as XXXX@gmail.com

(above I have replaced my gmail address with XXXX@gmail.com, to not invite spambots)

**Comment by ghost** [comment]
The second line says it all: `Coursera-dl v1.4.8 (lxml)`
The most recent version is **v1.4.11** this version uses the new coursera authentication urls/settings so it's obvious that old versions won't work just do `pip install --upgrade` and it should close this issue

**Comment by colablikje** [comment]
yes, that works like a charm, thanks!
