### ISSUE TITLE
Failed to download "[Errno 22] invalid mode ('wb') or filename"

### ISSUE THREAD

**Issue by ronlut** [dgorissen/coursera-dl#9]
Hi.
On windows, downloading the "An Introduction to Interactive Programming in Python" course, I'm getting the following error:

Failed to download url https://class.coursera.org/interactivepython-2012-001/wiki/view?page=week2 to c:\CoursEra\interactivepython-2012-001\04 - Week 2b - Buttons and input fields\02 - Input fields (934)\view?page=week2.html: [Errno 22] invalid mode ('wb') or filename: u'c:\CoursEra\interactivepython-2012-001\04 - Week 2b - Buttons and input fields\02 - Input fields (934)\view?page=week2.html'

Can you help me with that?
Thanks in advance.

**Comment by dgorissen** [comment]
I was unable to test with that class as the course had already closed. Did a small fix, let me know if it still breaks.

**Comment by ronlut** [comment]
Thanks! works now :+1:
