### ISSUE TITLE
Does not accept password with special characters

### ISSUE THREAD

**Issue by hanxue** [dgorissen/coursera-dl#92]
I am using a coursera password with the character '^' and **coursera-dl** keeps showing **Exception: Invalid username and password**. Logging in via the website directly works fine. 

Workaround: change password to alphanumerical string without special characters. 

Python: 2.7.2
OS: Windows 7 64bit

**Comment by ghost** [comment]
duplicate of issue https://github.com/dgorissen/coursera-dl/issues/82
